# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mail_form}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jos\303\251 Valim", "Carlos Ant\303\264nio"]
  s.date = %q{2010-05-26}
  s.description = %q{Send e-mail straight from forms in Rails with I18n, validations, attachments and request information.}
  s.email = %q{contact@plataformatec.com.br}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/generators/rails/mail_form_generator.rb",
     "lib/generators/rails/templates/model.rb",
     "lib/mail_form.rb",
     "lib/mail_form/base.rb",
     "lib/mail_form/delivery.rb",
     "lib/mail_form/notifier.rb",
     "lib/mail_form/shim.rb",
     "lib/mail_form/version.rb",
     "lib/mail_form/views/mail_form/contact.erb"
  ]
  s.homepage = %q{http://github.com/plataformatec/mail_form}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Send e-mail straight from forms in Rails with I18n, validations, attachments and request information.}
  s.test_files = [
    "test/mail_form_test.rb",
     "test/resource_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

